require("dotenv").config();
const express = require("express");
const cors = require("cors");
const searchRouter = require("./routes/search");
const app = express();
const PORT = Number(process.env.PORT) || 3000;
app.disable("x-powered-by");
app.use(cors({ origin: "*", methods: ["GET", "OPTIONS"] }));
app.use(express.json());
app.get("/", (req,res)=>res.json({sucesso:true,nome:"Nexa Radar API",versao:"2.1.1",rotaBusca:"/search?q=mouse"}));
app.get("/health", (req,res)=>res.json({sucesso:true,status:"online",uptime:Math.round(process.uptime())}));
app.use("/search", searchRouter);
app.use((req,res)=>res.status(404).json({sucesso:false,erro:"Rota não encontrada."}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({sucesso:false,erro:"Erro interno do servidor."});});
app.listen(PORT,"0.0.0.0",()=>console.log(`Nexa Radar API 2.1.1 ativa na porta ${PORT}`));
